# Generated by Django 5.2.12 on 2026-05-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='price',
        ),
    ]
