# Generated by Django 5.2.12 on 2026-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0002_remove_price_and_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='provider',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='providers',
            field=models.ManyToManyField(related_name='service_types', to='providers.serviceprovider'),
        ),
    ]
