# Generated by Django 5.2.12 on 2026-05-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0003_remove_servicetype_provider_servicetype_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='service_types', to='providers.serviceprovider'),
        ),
    ]
