# Generated by Django 5.2.12 on 2026-05-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from')), ('valid_to__isnull', True), ('valid_from__isnull', True), _connector='OR'), name='availability_valid_to_after_valid_from'),
        ),
    ]
