# Generated by Django 5.2.12 on 2026-05-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_availabilityslot_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set when the pre-appointment reminder email was sent.', null=True),
        ),
    ]
