# Generated by Django 5.2.12 on 2026-05-26 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_note'),
        ('providers', '0001_initial'),
        ('services', '0002_remove_price_and_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('client', 'start_time'), name='unique_client_start_time'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('client', 'service', 'start_time'), name='unique_client_service_start_time'),
        ),
    ]
